version: '3.5'
services:
  frontend:
    image: scrinii/pasta-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: scrinii/pasta-backend
    depends_on:
      - redis
  redis:
    image: redis:5
